const DEFAULT_FRIENDS = ["sam", "hunter", "amanda", "mick", "rod"];
const config = window.TRIP_SPLITTER_CONFIG || {};
const supabaseUrl = config.supabaseUrl || "";
const supabaseAnonKey = config.supabaseAnonKey || "";
const defaultTripId = config.defaultTripId || "";
const supabaseReady = supabaseUrl.startsWith("https://") && supabaseAnonKey.length > 20 && !supabaseUrl.includes("PASTE_") && !supabaseAnonKey.includes("PASTE_");
const hasDefaultTrip = defaultTripId.length > 20 && !defaultTripId.includes("PASTE_");
const db = supabaseReady ? supabase.createClient(supabaseUrl, supabaseAnonKey) : null;
let currentTripId = null, currentTripName = "trip", members = [], expenses = [], splits = [], selectedPayerId = null, channels = [];
const el = id => document.getElementById(id);
function money(value){return Number(value||0).toLocaleString(undefined,{style:"currency",currency:"USD"});}
function toast(message){const t=el("toast");t.textContent=String(message).toLowerCase();t.classList.add("show");setTimeout(()=>t.classList.remove("show"),1900);}
function safe(text){return String(text??"").replaceAll("&","&amp;").replaceAll("<","&lt;").replaceAll(">","&gt;").replaceAll('"',"&quot;").replaceAll("'","&#039;");}
function requireSupabase(){if(!supabaseReady){toast("check config.js.");return false;}return true;}
function requireTrip(){if(!requireSupabase())return false;if(!currentTripId){toast("default trip not loaded.");return false;}return true;}
async function loadDefaultTrip(){if(!requireSupabase())return;if(!hasDefaultTrip){toast("add default trip id in config.js.");render();return;}const {data,error}=await db.from("trips").select("*").eq("id",defaultTripId).single();if(error||!data){toast("default trip not found in supabase.");render();return;}currentTripId=data.id;currentTripName=data.name||"trip";subscribeToTrip();await refreshData();}
async function createDefaultFriendsIfMissing(){if(!currentTripId)return;const existingNames=members.map(m=>m.name.toLowerCase());const missingNames=DEFAULT_FRIENDS.filter(n=>!existingNames.includes(n));if(!missingNames.length)return;const rows=missingNames.map(name=>({trip_id:currentTripId,name}));const {error}=await db.from("trip_members").insert(rows);if(error)toast(error.message);}
async function refreshData(){if(!requireTrip())return;const [mr,er,sr]=await Promise.all([db.from("trip_members").select("*").eq("trip_id",currentTripId).order("created_at"),db.from("expenses").select("*").eq("trip_id",currentTripId).order("created_at",{ascending:false}),db.from("expense_splits").select("*").eq("trip_id",currentTripId)]);if(mr.error)return toast(mr.error.message);if(er.error)return toast(er.error.message);if(sr.error)return toast(sr.error.message);members=mr.data||[];expenses=er.data||[];splits=sr.data||[];await createDefaultFriendsIfMissing();if(members.length<DEFAULT_FRIENDS.length){const retry=await db.from("trip_members").select("*").eq("trip_id",currentTripId).order("created_at");if(!retry.error)members=retry.data||members;}if(!selectedPayerId||!members.some(m=>m.id===selectedPayerId))selectedPayerId=members[0]?.id||null;render();}
function subscribeToTrip(){if(!db||!currentTripId)return;channels.forEach(c=>db.removeChannel(c));channels=[];["trip_members","expenses","expense_splits"].forEach(table=>{const channel=db.channel(`${table}-${currentTripId}`).on("postgres_changes",{event:"*",schema:"public",table,filter:`trip_id=eq.${currentTripId}`},()=>refreshData()).subscribe();channels.push(channel);});}
function selectPayer(id){selectedPayerId=id;render();}
function selectAllSplit(){document.querySelectorAll("#split-between input[type='checkbox']").forEach(b=>b.checked=true);}
function clearSplit(){document.querySelectorAll("#split-between input[type='checkbox']").forEach(b=>b.checked=false);}
async function uploadReceipt(file){if(!file)return null;const cleanName=file.name.toLowerCase().replace(/[^a-z0-9._-]/g,"-");const path=`${currentTripId}/${crypto.randomUUID()}-${cleanName}`;const {error}=await db.storage.from("receipts").upload(path,file,{cacheControl:"3600",upsert:false});if(error){toast(`receipt upload skipped: ${error.message}`);return null;}const {data}=db.storage.from("receipts").getPublicUrl(path);return data?.publicUrl||null;}
async function addPurchase(){if(!requireTrip())return;const description=el("description").value.trim().toLowerCase();const amount=Number(el("amount").value);const file=el("receipt").files?.[0]||null;const splitMemberIds=[...document.querySelectorAll("#split-between input[type='checkbox']:checked")].map(b=>b.value);if(!selectedPayerId)return toast("choose who paid.");if(!description)return toast("add what it was.");if(!amount||amount<=0)return toast("add a valid amount.");if(!splitMemberIds.length)return toast("choose who split it.");const receiptUrl=await uploadReceipt(file);const {data:expense,error:expenseError}=await db.from("expenses").insert({trip_id:currentTripId,description,amount:Math.round(amount*100)/100,payer_member_id:selectedPayerId,receipt_url:receiptUrl}).select().single();if(expenseError)return toast(expenseError.message);const splitRows=splitMemberIds.map(memberId=>({trip_id:currentTripId,expense_id:expense.id,member_id:memberId}));const {error:splitError}=await db.from("expense_splits").insert(splitRows);if(splitError)return toast(splitError.message);el("description").value="";el("amount").value="";el("receipt").value="";await refreshData();selectAllSplit();}
async function deletePurchase(expenseId){if(!requireTrip())return;if(!confirm("delete this purchase?"))return;const {error}=await db.from("expenses").delete().eq("id",expenseId);if(error)return toast(error.message);await refreshData();}
function calculateBalances(){const balances={};members.forEach(m=>balances[m.id]=0);expenses.forEach(e=>{const es=splits.filter(s=>s.expense_id===e.id);if(!es.length)return;balances[e.payer_member_id]+=Number(e.amount);const share=Number(e.amount)/es.length;es.forEach(s=>balances[s.member_id]-=share);});Object.keys(balances).forEach(id=>balances[id]=Math.round(balances[id]*100)/100);return balances;}
function calculateSettlements(){const balances=calculateBalances();const debtors=Object.entries(balances).filter(([,a])=>a<-0.005).map(([id,a])=>({id,amount:Math.abs(a)})).sort((a,b)=>b.amount-a.amount);const creditors=Object.entries(balances).filter(([,a])=>a>0.005).map(([id,a])=>({id,amount:a})).sort((a,b)=>b.amount-a.amount);const settlements=[];let i=0,j=0;while(i<debtors.length&&j<creditors.length){const payment=Math.min(debtors[i].amount,creditors[j].amount);settlements.push({fromId:debtors[i].id,toId:creditors[j].id,amount:Math.round(payment*100)/100});debtors[i].amount-=payment;creditors[j].amount-=payment;if(debtors[i].amount<0.005)i++;if(creditors[j].amount<0.005)j++;}return settlements;}
function memberName(id){return members.find(m=>m.id===id)?.name||"unknown";}
function render(){el("config-warning").classList.toggle("hidden",supabaseReady&&hasDefaultTrip);el("purchaser-buttons").innerHTML=members.length?members.map(m=>`<button class="person ${m.id===selectedPayerId?"active":""}" onclick="selectPayer('${m.id}')">${safe(m.name)}</button>`).join(""):DEFAULT_FRIENDS.map(n=>`<button class="person" disabled>${safe(n)}</button>`).join("");el("friends").innerHTML=members.length?members.map(m=>`<div class="pill"><strong>${safe(m.name)}</strong></div>`).join(""):`<div class="empty">loading people.</div>`;el("split-between").innerHTML=members.length?members.map(m=>`<label class="check-row"><input type="checkbox" value="${m.id}" checked><span>${safe(m.name)}</span></label>`).join(""):`<div class="empty">loading split options.</div>`;const balances=calculateBalances();el("balances").innerHTML=members.length?members.map(m=>{const amount=balances[m.id]||0;return `<div class="pill"><span>${safe(m.name)}</span><span class="${amount>=0?"money-positive":"money-negative"}">${amount>=0?"gets":"owes"} ${money(Math.abs(amount))}</span></div>`;}).join(""):`<div class="empty">loading balances.</div>`;const settlements=calculateSettlements();el("settlements").innerHTML=settlements.length?settlements.map(s=>`<div class="pill"><span><strong>${safe(memberName(s.fromId))}</strong> pays <strong>${safe(memberName(s.toId))}</strong></span><span class="amount">${money(s.amount)}</span></div>`).join(""):`<div class="empty">all settled, or no shared purchases yet.</div>`;el("purchases").innerHTML=expenses.length?expenses.map(e=>{const es=splits.filter(s=>s.expense_id===e.id);const splitNames=es.map(s=>safe(memberName(s.member_id))).join(", ");return `<div class="purchase-card"><div class="purchase-top"><div><strong>${safe(e.description)}</strong><div class="small muted">paid by ${safe(memberName(e.payer_member_id))} · split with ${splitNames}</div>${e.receipt_url?`<a class="receipt-link" href="${safe(e.receipt_url)}" target="_blank" rel="noopener">view receipt</a>`:""}</div><div class="right-actions"><div class="amount">${money(e.amount)}</div><button class="danger" onclick="deletePurchase('${e.id}')">delete</button></div></div></div>`;}).join(""):`<div class="empty">no purchases yet.</div>`;}
function bindEvents(){el("add-purchase-button").addEventListener("click",addPurchase);el("select-all-button").addEventListener("click",selectAllSplit);el("clear-split-button").addEventListener("click",clearSplit);el("refresh-button").addEventListener("click",refreshData);}
window.addEventListener("load",async()=>{bindEvents();render();await loadDefaultTrip();});
